var dir_ef4237a93dae04612d5902be380c112e =
[
    [ "ArmorDyeRecipe.cpp", "ArmorDyeRecipe_8cpp_source.html", null ],
    [ "ArmorDyeRecipe.h", "ArmorDyeRecipe_8h_source.html", null ],
    [ "ArmorRecipes.cpp", "ArmorRecipes_8cpp_source.html", null ],
    [ "ArmorRecipes.h", "ArmorRecipes_8h_source.html", null ],
    [ "ClothDyeRecipes.cpp", "ClothDyeRecipes_8cpp_source.html", null ],
    [ "ClothDyeRecipes.h", "ClothDyeRecipes_8h_source.html", null ],
    [ "FireworksRecipe.cpp", "FireworksRecipe_8cpp_source.html", null ],
    [ "FireworksRecipe.h", "FireworksRecipe_8h_source.html", null ],
    [ "FoodRecipes.cpp", "FoodRecipes_8cpp_source.html", null ],
    [ "FoodRecipes.h", "FoodRecipes_8h_source.html", null ],
    [ "FurnaceRecipes.cpp", "FurnaceRecipes_8cpp_source.html", null ],
    [ "FurnaceRecipes.h", "FurnaceRecipes_8h_source.html", null ],
    [ "MapCloningRecipe.h", "MapCloningRecipe_8h_source.html", null ],
    [ "MapExtendingRecipe.h", "MapExtendingRecipe_8h_source.html", null ],
    [ "OreRecipes.cpp", "OreRecipes_8cpp_source.html", null ],
    [ "OreRecipes.h", "OreRecipes_8h_source.html", null ],
    [ "Recipes.cpp", "Recipes_8cpp_source.html", null ],
    [ "Recipes.h", "Recipes_8h_source.html", null ],
    [ "Recipy.h", "Recipy_8h_source.html", null ],
    [ "ShapedRecipy.cpp", "ShapedRecipy_8cpp_source.html", null ],
    [ "ShapedRecipy.h", "ShapedRecipy_8h_source.html", null ],
    [ "ShapelessRecipy.cpp", "ShapelessRecipy_8cpp_source.html", null ],
    [ "ShapelessRecipy.h", "ShapelessRecipy_8h_source.html", null ],
    [ "StructureRecipes.cpp", "StructureRecipes_8cpp_source.html", null ],
    [ "StructureRecipes.h", "StructureRecipes_8h_source.html", null ],
    [ "ToolRecipes.cpp", "ToolRecipes_8cpp_source.html", null ],
    [ "ToolRecipes.h", "ToolRecipes_8h_source.html", null ],
    [ "WeaponRecipes.cpp", "WeaponRecipes_8cpp_source.html", null ],
    [ "WeaponRecipes.h", "WeaponRecipes_8h_source.html", null ]
];