#pragma once
#define IDC_CamX "CamX"
#define IDC_CamZ "CamZ"
#define IDC_YRot "YRot"
#define IDC_CamY "CamY"
#define IDC_Elevation "Elevation"
#define IDC_XuiLabel1 "XuiLabel1"
#define IDC_XuiLabel2 "XuiLabel2"
#define IDC_XuiLabel3 "XuiLabel3"
#define IDC_XuiLabel4 "XuiLabel4"
#define IDC_XuiLabel7 "XuiLabel7"
#define IDC_LockPlayer "LockPlayer"
#define IDC_Teleport "Teleport"
#define IDC_XuiDebugSetCamera "XuiDebugSetCamera"
