#pragma once
#define IDC_Background3 "Background3"
#define IDC_Background2 "Background2"
#define IDC_Background1 "Background1"
#define IDC_control_ListItem "control_ListItem"
#define IDC_control_ListItem "control_ListItem"
#define IDC_control_ListItem "control_ListItem"
#define IDC_control_ListItem "control_ListItem"
#define IDC_control_ListItem "control_ListItem"
#define IDC_XuiListGamers "XuiListGamers"
#define IDC_XuiTextFilter "XuiTextFilter"
#define IDC_XuiTextLeaderboard "XuiTextLeaderboard"
#define IDC_XuiTextEntries "XuiTextEntries"
#define IDC_XuiTextInfo "XuiTextInfo"
#define IDC_LSIcon "LSIcon"
#define IDC_RBIcon "RBIcon"
#define IDC_LBIcon "LBIcon"
#define IDC_SceneLeaderboards "SceneLeaderboards"
