#pragma once
#define IDC_XuiSlider "XuiSlider"
#define IDC_FocusSink "FocusSink"
#define IDC_XuiSliderUISizeSplitscreen "XuiSliderUISizeSplitscreen"
#define IDC_XuiSlider "XuiSlider"
#define IDC_FocusSink "FocusSink"
#define IDC_XuiSliderUISize "XuiSliderUISize"
#define IDC_XuiShowSplitscreenGamertags "XuiShowSplitscreenGamertags"
#define IDC_XuiSplitScreen "XuiSplitScreen"
#define IDC_XuiShowAnimatedCharacter "XuiShowAnimatedCharacter"
#define IDC_XuiDisplayDeathMessages "XuiDisplayDeathMessages"
#define IDC_XuiDisplayHand "XuiDisplayHand"
#define IDC_XuiDisplayHUD "XuiDisplayHUD"
#define IDC_SceneSettingsUI "SceneSettingsUI"
