#pragma once
#define IDC_CheckboxHostInvisible "CheckboxHostInvisible"
#define IDC_CheckboxHostHunger "CheckboxHostHunger"
#define IDC_CheckboxHostFly "CheckboxHostFly"
#define IDC_ButtonKick "ButtonKick"
#define IDC_CheckboxTeleport "CheckboxTeleport"
#define IDC_CheckboxOp "CheckboxOp"
#define IDC_CheckboxAttackAnimals "CheckboxAttackAnimals"
#define IDC_CheckboxAttackPlayers "CheckboxAttackPlayers"
#define IDC_CheckboxUseContainers "CheckboxUseContainers"
#define IDC_CheckboxUseDoorsAndSwitches "CheckboxUseDoorsAndSwitches"
#define IDC_CheckboxBuildAndMine "CheckboxBuildAndMine"
#define IDC_Gamertag "Gamertag"
#define IDC_Icon "Icon"
#define IDC_InGamePlayerOptions "InGamePlayerOptions"
