#pragma once
#define IDC_XuiDifficultyText "XuiDifficultyText"
#define IDC_XuiSlider "XuiSlider"
#define IDC_FocusSink "FocusSink"
#define IDC_XuiSliderDifficulty "XuiSliderDifficulty"
#define IDC_XuiSlider "XuiSlider"
#define IDC_FocusSink "FocusSink"
#define IDC_XuiSliderAutosave "XuiSliderAutosave"
#define IDC_XuiMashUpWorlds "XuiMashUpWorlds"
#define IDC_XuiInGameGamertags "XuiInGameGamertags"
#define IDC_XuiShowTooltips "XuiShowTooltips"
#define IDC_XuiShowHints "XuiShowHints"
#define IDC_XuiViewBob "XuiViewBob"
#define IDC_SceneSettingsOptions "SceneSettingsOptions"
